---------------------------------------------------------------------------------------------------------------
-- Business Insights : -

SELECT * FROM customer_shopping_purchase_insights
LIMIT 10

UPDATE customer_shopping_purchase_insights
SET purchase_amount = ROUND(purchase_amount::numeric, 2)

ALTER TABLE customer_shopping_purchase_insights
RENAME TO shopping_data

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, ROUND(sum(purchase_amount)::numeric,2) as total_revenue
FROM shopping_data
GROUP BY gender
ORDER BY total_revenue DESC



--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM shopping_data
WHERE (discount_applied = 'Yes') AND
	  (purchase_amount > (SELECT AVG(purchase_amount) FROM shopping_data))


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(avg(review_rating)::NUMERIC,2) as avg_review_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(avg(purchase_amount)::NUMERIC,2) as avg_purchase_amount
FROM shopping_data
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT subscription_status, ROUND(sum(purchase_amount)::numeric,2)  as Total_purchase_amount, 
							avg(purchase_amount)  as avg_purchase_amount,
							COUNT(*) AS total_customers
FROM shopping_data
GROUP BY subscription_status
ORDER BY Total_purchase_amount DESC


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, COUNT(case WHEN discount_applied = 'Yes' THEN 1 END) AS discounted_purchase,
					   COUNT(*) AS total_purchase,
					   TO_CHAR((COUNT(case WHEN discount_applied = 'Yes' 
					   THEN 1 END)*100/COUNT(*)),'99%') AS discounted_purchase_rate
FROM shopping_data
GROUP BY item_purchased
ORDER BY discounted_purchase_rate DESC
LIMIT 5


--Q7. Segment customers into New, Returning, and Loyal based on their 
--total number of previous purchases, and show the count of each segment.
SELECT CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS loyalty_bracket,
			COUNT(*) total_purchase
FROM shopping_data
GROUP BY CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END
ORDER BY total_purchase DESC


--Q8. What are the top 3 most purchased products within each category? 
WITH prodranking as
	(SELECT category,  item_purchased as top_items, COUNT(*) as total_purchsed,
	   DENSE_RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
	FROM shopping_data
GROUP BY category,item_purchased
ORDER BY category)

SELECT category,top_items,total_purchsed
FROM prodranking
WHERE prodranking.rnk <=3 


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT age_group, ROUND(sum(purchase_amount)::NUMERIC,2) as total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC

